### ISSUE TITLE
Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by junioramilson** [smalltalk-ai/api-ai-botkit-facebook#13]
/app/node_modules/api-ai-botkit-facebook/api-ai-botkit-facebook.js:36
worker.apiaiService = apiai(config.token);

**Comment by jsalwen** [comment]
The readme.md needs an update. Should be
```js
const apiai = apiaibotkit({token: 'some-API.ai-token'});
```

**Comment by smalltalk-josh** [comment]
The documentation has been updated.
